name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: |
          sudo apt install -y libcppunit-dev
          ls
          chmod 777 configure.sh
      - name: configure
        run: ./configure.sh
      - name: make
        run: make
      - name: make test
        run: |
              make test
      - name: 1. Compile
        run: make build
      - name: 2. Run executable
        run: ./main
      - name: 3. Generate reports
        run: |
            make lcov-report
            make gcovr-report
