name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: |
          sudo apt install -y libcppunit-dev
          sudo apt-get -y install lcov
          chmod 777 configure.sh
      - name: configure
        run: ./configure.sh
      - name: make
        run: make
      - name: make test
        run: |
              make test
              pip install gcovr
      - name: generate Test coverage report
        run: gcov helloTest.cpp
      - name: generate HTML coverage report
        run: | 
             lcov --capture --directory . --output-file coverage.info
             genhtml coverage.info
             ls
             sudo apt-get install xvfb
             touch ~/.Xauthority
             xauth generate :0 . trusted
             xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)
             xauth list
             export DISPLAY=:0
             firefox coverage.info
