name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: |
          sudo apt install -y libcppunit-dev
          sudo apt-get -y install lcov
          chmod 777 configure.sh
      - name: configure
        run: ./configure.sh
      - name: make
        run: make
      - name: make test
        run: |
              make test
              pip install gcovr
      - name: generate Test coverage report
        run: gcov -b -c -i helloTest.cpp 
      - name: generate HTML coverage report
        run: | 
             lcov --capture --directory . --output-file coverage.info
             genhtml -o coverage.info
             ls
             sudo apt-get install xvfb
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
        
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
             html_file: 'index.html'
